### ISSUE TITLE
List all sessions in allsessions page

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#1]
* Lists all YouTube hangout sessions.
* Lists all upcoming sessions information
* Shows information about past and upcoming speakers.

**Comment by tapaswenipathak** [comment]
Like : http://www.mycodeschool.com/videos

**Comment by vaibhavsingh97** [comment]
@tapasweni-pathak I am interested in working on this issue

**Comment by tapaswenipathak** [comment]
@vaibhavsingh97 Sure, assigned this to you.

**Comment by abarya** [comment]
Hi @tapasweni-pathak,
I'd like to work on this issue. A few things on which I need some clearity,
- Do I need to remove the upcoming sessions info from the home page?
- In case of past speakers, what all do I need to provide? I think of something like below:

> Past Speakers
[Joannah Nanjekye](https://github.com/nanjekyejoannah)

The link will be of their personal website or github profile.
Any suggestions on this?

**Comment by tapaswenipathak** [comment]
@abhishekarya286 Great! we would like to have something similar as [this](http://www.mycodeschool.com/videos) for 1 linked to ```sessions``` on homepage, which currently links to the YouTube channel. First embed the YouTube session and then a new page.

For second, upcoming session will remain on the home page where they are.
For 3, when the user click on the session link, a new page will open having the info what we have in YouTube description of the video.

**Comment by abarya** [comment]
@tapasweni-pathak, thanks for the info.

**Comment by tapaswenipathak** [comment]
@abhishekarya286 :wave: working on this?

**Comment by abarya** [comment]
Nope
