### ISSUE TITLE
Add the Documentation of the website and contributing guide to Read the Docs

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#102]
Currently the documentation of the website is explained in [README](https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/blob/develop/README.md).

It will be good to have the information about 
1. branches
2. hound, travis enablement
3. installation instruction
4. issue and labels

available on [Read the Docs](http://docs.readthedocs.io/en/latest/getting_started.html).

**Comment by vaibhavsingh97** [comment]
@tapasweni-pathak Google open sourced Google Developer documentation style guide. We can use it to bootstrap our own style guide. Read more about here  https://opensource.googleblog.com/2017/09/making-google-developers-documentation.html?m=1
We can use this for documentation.
Cc: @nikhita @anubhakushwaha @sandarumk
What are your opinion?

**Comment by tapaswenipathak** [comment]
@vaibhavsingh97 We can compare these two before going ahead with one. ReadTheDocs is quite established project made to fulfill the needs of documentation required and used widely by many projects. It has search and components it used underneath are also open source. Not sure about Google Developer documentation style guide, would like to know. 

Also can you please explain a bit more about we can bootstrap our own style guide, I didn't quite clearly get this.
