### ISSUE TITLE
Remove django-registration-redux

### ISSUE THREAD

**Issue by anubhakushwaha** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#104]
**FEATURE REQUEST**:

**Description**:
To keep things clean and in order, removal of django-registration-redux before creating a custom-registration model.

**Comment by vaibhavsingh97** [comment]
@tapasweni-pathak @anubhakushwaha @nikhita Do I have to remove test cases too?

**Comment by anubhakushwaha** [comment]
@vaibhavsingh97  I guess it makes no sense to have tests for something that has been removed, though even for custom registration we will have similar tests but for now it's advisable to keep things together i.e have unit tests for the functionality together in the same PR.

**Comment by vaibhavsingh97** [comment]
@anubhakushwaha I am removing test cases for now, we will add when we have custom-registration-model
