### ISSUE TITLE
Unable to sign up and sign in

### ISSUE THREAD

**Issue by abarya** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#108]
I tried to sign up a lot of times but was unable to do so.

**Comment by vaibhavsingh97** [comment]
@abhishekarya286 Are you trying to signup and signin locally or on Heroku??
As of now we are dropping django-registration-redux and we will use our own custom registration model.
I already sent #106 to revert the changes and after that i will send another PR with custom registration model

**Comment by abarya** [comment]
Both of these are not working for me.

**Comment by anubhakushwaha** [comment]
@abhishekarya286 Thanks for raising the issue, but since we are migrating to custom-registration model I am closing this, feel free to raise any issue/feature :)

**Comment by nikhita** [comment]
Is this still an issue? 

cc @abhishekarya286 @anubhakushwaha

**Comment by abarya** [comment]
@nikhita I can't see registration page now.

**Comment by vaibhavsingh97** [comment]
@abhishekarya286 visit: http://opensourcehelpcommunity-predev.herokuapp.com/
Note: If you succesfully signup then you will be greeted by `Internal Server Error` and you can login

**Comment by vaibhavsingh97** [comment]
This is not an error, as SMTP is not configured till now, that's why you get `Internal Server Error` as app tries to send email for verfication purpose.
Also, you can help with #174 😄

**Comment by tapaswenipathak** [comment]
👋 Closing this one as predev has which we need to test and separate issue for this.
