### ISSUE TITLE
the browser is zoomed out and the navbar menu doesn't open in mobile screen  

### ISSUE THREAD

**Issue by mohamedragaey** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#11]
1-missing meta tag `<meta name="viewport" content="width=device-width, initial-scale=1">` 

> This means that the browser will (probably) render the width of the page at the width of its own screen. So if that screen is 320px wide, the browser window will be 320px wide, rather than way zoomed out and showing 960px (or whatever that device does by default

2-the order of the scripts " jquery.js,bootstrap.js" is wrong. the jquery.js must be called before bootstrap.js. because that the bootstrap.js require jquery.js to render first to work smoothly  
3-add the `.collapsed` class to the button on the navigation

**Comment by tapaswenipathak** [comment]
@mohamedragaey Why 3rd?

**Comment by mohamedragaey** [comment]
@tapasweni-pathak it is more descriptive that tells you if the button is clicked or not, and let you know whether the menu was opened by this button or another button.
