### ISSUE TITLE
dev is down with no such table: main_chatsession

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#110]
[![Screenshot from Gyazo](https://gyazo.com/f0a82b6f70538c8c4a2e359bcf0d92e6/raw)](https://gyazo.com/f0a82b6f70538c8c4a2e359bcf0d92e6)

#106 caused it. #109 did not fix it. I tried to remove migrations
```
python manage.py makemigrations
python manage.py migrate
```
after deleting db.sqlite3. This did not fix the issue. I also got few suggestions on completely removing sqlite3 as this doesn't go quite well with Heroku and have Postgres instead; please let me know your thoughts on this. 
@vaibhavsingh97 @anubhakushwaha Please look into it. Let me know if you need access to Heroku. I will update this issue with commit having the steps to make a Django app on Heroku live, you can push to that and fix instead of main develop or master. 

We can create one more for predev before pushing on develop, where we can try out things.

**Comment by anubhakushwaha** [comment]
@tapasweni-pathak Yeah please provide access to Heroku and yes pretesting where we can try different things sounds good, please update this issue

**Comment by vaibhavsingh97** [comment]
@tapasweni-pathak Yes, please provide us access and having `pretest` sounds good where we can try out new things.

**Comment by tapaswenipathak** [comment]
I have created predev branch and on Heroku the app is opensourcehelpcommunity-predev. I have also shared the access of this with both of you. Please let me know if there are any issues.

**Comment by jarifibrahim** [comment]
@tapasweni-pathak @vaibhavsingh97 The commit https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/commit/d1ec086f01428d87a7453d919490e0606ee0d495 removed the database settings for Heroku.

Heroku does not have any file system so SQLite will never work. We're using Postgres on Heroku. The environment variable `DATABASE_URL` on Heroku contains the connection URL.

I've sent a PR to fix this https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/pull/136

**Comment by jarifibrahim** [comment]
@tapasweni-pathak Once the PR is merged someone will have to run `python manage.py migrate` on Heroku. This should create the necessary tables.
