### ISSUE TITLE
Redirect to new 404 and 403 page in case of these errors

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#111]
We have debug turned on develop, should we turn it off there? 

Also on the main one I tried access a 404 and got a screen like this. User should be redirected to a specific 404 informative page and after we merge user registration, login we also need 403 page. 

[![Screenshot from Gyazo](https://gyazo.com/7f7e5dc9e013d1a1c169a9669925eef7/raw)](https://gyazo.com/7f7e5dc9e013d1a1c169a9669925eef7)

**Comment by bhatiatanish** [comment]
I'd like to take up this issue. Can you assign me that?

**Comment by nikhita** [comment]
@bhatiatanish Only collaborators and members of a Github org can be assigned. However, consider yourself assigned and feel free to work on it. :)

**Comment by tapaswenipathak** [comment]
Closed with e88dada9165036a58e73426bdec83a7d7c23da75.
