### ISSUE TITLE
Functionality to view previous requests for sessions

### ISSUE THREAD

**Issue by anubhakushwaha** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#116]
**FEATURE REQUEST**:

**Description**:

As of the current scenario, the user can request for sessions, adding this feature would allow the user to go through his history of requests, I am still not sure if this functionality will be of any specific use or not, let me know your opinions @OpenSourceHelpCommunity/everyone , follow up of #96

**Comment by nikhita** [comment]
Sounds good. :+1: 

> I am still not sure if this functionality will be of any specific use or not

We can probably have this as a "lower" priority compared to other features but would be definitely nice-to-have.

**Comment by amarlearning** [comment]
> I am still not sure if this functionality will be of any specific use or not

@anubhakushwaha this will definitely be a good add-on. I think @tapasweni-pathak proposed this idea before also to make a separate view tab for all the hosted sessions. 

I think this should be a medium priority issue. :+1:

**Comment by abarya** [comment]
I'd like to take up this issue @anubhakushwaha

**Comment by anubhakushwaha** [comment]
@abhishekarya286 Thanks for making an initiative, exactly how we will go ahead with this needs a bit more discussion, as soon as things are clear you can work on it, anyways what are your thoughts on this? As in how do you suggest implementing this for the most optimal use?

**Comment by tapaswenipathak** [comment]
I think we are getting confused in showing all sessions and showing the sessions which the user requested before. I would suggest not to handle the case for user to show their previous request. As user can request session from anyone by using this feature in the website, we take it as a request and we do not work on providing the details about their previous request. A kind like user requests a register variable from CPU, our choice here.

#1 is for other part. @abhishekarya286 let us know if you would like to take that up, closing this one.
