### ISSUE TITLE
Functionality to view all contests at one place

### ISSUE THREAD

**Issue by vaibhavsingh97** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#118]
## **FEATURE REQUEST:**

**Description**:
As of now users struggle to search various open source competition where beginners can contribute. Competitions like Codeheat, Hactoberfest (About to start), etc. are beginner friendly but only some of them know. So if we collect all the information and list them on our website. Please let me know your opinions @OpenSourceHelpCommunity/everyone

**Comment by nikhita** [comment]
+1. Had no idea about Codeheat.

**Comment by anubhakushwaha** [comment]
@vaibhavsingh97 It's an awesome idea

**Comment by tapaswenipathak** [comment]
1. User signin
2. Click on submit a contest
3. Add information like Name, link, description, start date, end date, other info about the contest -> submit [new table in db]
4. A page on main website, opensourcecontests fetches info and shows.

**Comment by abarya** [comment]
Hi @tapasweni-pathak,
I've started working on this. Will do it by tomorrow.
