### ISSUE TITLE
Addition of new labels to tag issues

### ISSUE THREAD

**Issue by vaibhavsingh97** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#122]
Following labels are needed :

    has-pr : To tag issues which already has a PR.

**Comment by nikhita** [comment]
Should it be `has-PR`? or `has-pr`? Both of them look weird to me. :thinking: 

Maybe just `assigned`? The point is someone is working on the issue and it is not free to be taken by others. It's not necessary that the person who wants to work on it has already sent a PR, maybe there are still working on it.

@vaibhavsingh97 wdyt?

**Comment by vaibhavsingh97** [comment]
@nikhita I think we need both labels, as i f someone already sent the PR then we can use `has-pr` and if no in sent the PR but already working on the issue, we can add `assigned`.

**Comment by tapaswenipathak** [comment]
I would say a no to this, as the committer should be suggested to link the issue with the pull request so that anyone can see, we need not explicitly keep track of it.

**Comment by anubhakushwaha** [comment]
Closing this.
