### ISSUE TITLE
PR template: remove status checkboxes

### ISSUE THREAD

**Issue by nikhita** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#123]
Piggybacking the discussion from https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/pull/121#issuecomment-330743617:

- update the labels to list out the word `status` explicitly. 
- remove the checkboxes from the PR template.

**Comment by vaibhavsingh97** [comment]
@nikhita I think the labels issue should be addressed seperately as after merging the PR, github will close this issue.

**Comment by nikhita** [comment]
@vaibhavsingh97 Shouldn't be a big problem, I'll update the labels in a bit.

**Comment by nikhita** [comment]
Updated the labels. Now, we have:

1. `status: Needs Review`
2. `status: In Development`
3. `status: On Hold`
4. `status: Needs Merge`

Let me know if this is fine. If there are any changes to be made, I'll update the labels accordingly.

**Comment by vaibhavsingh97** [comment]
@nikhita It's perfect 🎉
