### ISSUE TITLE
Add a pre-linting file

### ISSUE THREAD

**Issue by abarya** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#130]
I think there is a need to add a file that can check for linting errors before pushing changes to the remote repo.

**Comment by vaibhavsingh97** [comment]
@abhishekarya286 Please use issue template to create new issue. 😄
Also, Please mention example/screenshot/link wherever necessary. Thanks 😄 
Are you talking about editorconfig?

**Comment by jarifibrahim** [comment]
@vaibhavsingh97 We should add linter config files and configure Travis CI to perform linting on our code. This process ensures that all the code we write follows the standard convention.
[Pylint](https://www.pylint.org/) is one such linter for Python.

**Comment by vinaypuppal** [comment]
Hi guys, can I work on this?

These are the things I am thinking to implement in PR
- [ ] Configure [Flake8](https://medium.com/python-pandemonium/what-is-flake8-and-why-we-should-use-it-b89bd78073f2) linter.
- [ ] Configure [yapf](https://github.com/google/yapf) (a python code formatter from google).
- [ ] Configure [pre-commit](http://pre-commit.com/) so `flake8` and `yapf` are run for every `git commit`.
- [ ] Update `Readme` on how to install `pre-commit` hooks.

**Comment by anubhakushwaha** [comment]
@vinaypuppal  Thanks for bringing such a cool thing like yapf, I went through it's documentation and think it would be really useful for us. cc @tapasweni-pathak  @jarifibrahim  @vaibhavsingh97  What do you think :smile:

**Comment by vaibhavsingh97** [comment]
Thanks @vinaypuppal for introducing yapf to us ✨ and feel free to send PR. @anubhakushwaha Yeah! It will be useful for us. 👍

**Comment by vinaypuppal** [comment]
Sure @vaibhavsingh97 

Yes its an awesome tool which I found recently while searching for python alternative for [prettier](https://github.com/prettier/prettier)(an awesome opinionated code formatter tool in javascript ecosystem). 
BTW, prettier team is working on python support as well.(https://github.com/prettier/prettier-python) but its under development.
