### ISSUE TITLE
Finished Session in Upcoming Sessions

### ISSUE THREAD

**Issue by sandarumk** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#131]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in our slack channel at https://opensourcehelp.slack.com/. Request invite [here](https://opensourcehelp.herokuapp.com)

**Description**:

In the "Upcoming Sessions" section in the website should only show the upcoming scheduled. Currently, it shows an already finished session.

**Expected Behavior**:

Already finished sessions should not be included in the upcoming sessions

**Actual Behavior**:

The session which was finished is included under the upcoming sessions 

**Steps to Reproduce**:
Go to home page of the Open Source Help Community's Webpage

**Screenshots (if any)**:
![capture](https://user-images.githubusercontent.com/1345681/31493889-bea07e20-af6e-11e7-9d70-0042545db982.PNG)

**Would you like to work on this issue?**
- [ ] Yes
- [x] No

**Comment by vaibhavsingh97** [comment]
@sandarumk I already sent PR and it's merged. It's that it's not reflected to master branch 😄 so main website don't have this feature

**Comment by tapaswenipathak** [comment]
The master branch keeps the session details on the main website until next is not announced. This will be fixed with next session soon. What we can do is after the session completes, the register now should be changed to view the session linking to the YouTube link.

**Comment by tapaswenipathak** [comment]
For now 8da0e7b005de30f4ff9a7843f60607be86bc05ca closes this.
