### ISSUE TITLE
Not compatible with different screens

### ISSUE THREAD

**Issue by vaibhavsingh97** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#14]
![screenshot 1](https://cloud.githubusercontent.com/assets/8705386/26367853/a2859cb4-400d-11e7-801c-e14047e457fa.png)

**Comment by tapaswenipathak** [comment]
This looks fine, may be I am missing something. What could have been better?

**Comment by vaibhavsingh97** [comment]
I will fix it. Can we move from Bootstrap to [materializecss](http://materializecss.com/) framework?

**Comment by tapaswenipathak** [comment]
Feel free to submit a design change or a pull request where we can understand what you want to change and to what.

**Comment by anubhakushwaha** [comment]
@vaibhavsingh97 What issue were you facing and please let us know the devices you are trying on as well,thanks a lot,we appreciate your efforts :)

**Comment by vaibhavsingh97** [comment]
@anubhakushwaha I was testing the screen compatibility i.e. look and feel of websites on the different screen.
Tool used: Chrome Developer option.
Screen size i have tested are: 414x736, 412x732, 360x640, 768x1024 

To explain the issue I am taking the example of [ICHSA 2018](https://ichsa2018.com/).
Website screenshot Desktop mode: ![screenshot 1](https://cloud.githubusercontent.com/assets/8705386/26647893/6a5cb5d2-465e-11e7-98c1-ffc4f5c33883.png)
Website Screenshot Mobile Mode: ![screenshot 2](https://cloud.githubusercontent.com/assets/8705386/26647973/9b3b40a6-465e-11e7-9bca-a38c4bdbad0e.png)

OSHC website actual behaviour:![screenshot 5](https://cloud.githubusercontent.com/assets/8705386/26648044/d58c6a6e-465e-11e7-8327-1374e5364e21.png)
OSHC expected behaviour: It should adapt different screen view and give enhanced user experience

I am interested in changing the look and feel of the website to latest material design standard and screen compatibility.

**Comment by anubhakushwaha** [comment]
@vaibhavsingh97 Sounds great,keep us updated with all what you are planning to do and how so that we all can work along to give the best results :)

**Comment by vaibhavsingh97** [comment]
@anubhakushwaha I will create the new issue with wireframes after Monday both for website and forum

**Comment by tameeshB** [comment]
@vaibhavsingh97 I think what you are trying to say is that you want to make the site more responsive, If I have interpreted it right? In that case, the following can be achieved by adding a single line of HTML markup
<img width="1393" alt="screen shot 2017-06-02 at 9 25 12 am" src="https://cloud.githubusercontent.com/assets/20886076/26710135/6fcac65e-4775-11e7-8c1a-5cfa75f8ee8f.png">

Markup : `<meta name="viewport" content="width=device-width, initial-scale=1">`
Bootstrap is well known for its grid layout and responsiveness, Switching to materialize for just responsiveness shouldn't be necessary.

**Comment by tapaswenipathak** [comment]
@vaibhavsingh97 @tameeshB Woops, We already have this in header, looks like some other issues is causing such behavior.

**Comment by tameeshB** [comment]
@tapasweni-pathak @vaibhavsingh97 In that case, doesn't look like it is getting rendered:
[
<img width="742" alt="screen shot 2017-06-02 at 9 40 58 am" src="https://cloud.githubusercontent.com/assets/20886076/26710468/b6317938-4777-11e7-860d-dd49c2b7c600.png">
](url)
[view-source:http://opensourcehelpcommunity.herokuapp.com/](view-source:http://opensourcehelpcommunity.herokuapp.com/)

**Comment by tapaswenipathak** [comment]
@tameeshB Yes, I saw this in your previous screenshot. I think I found the issue, will be pushing the change.

**Comment by vaibhavsingh97** [comment]
@tameeshB yeah! still, the menu is not accessible. I am just thinking of new design as it looks quite old and for that, i will submit wireframes soon ....as i have semester exams going on so you have to wait till Monday
@tapasweni-pathak We can move to  .com domain which will be free for one year and after that, we all can contribute. Please share your views

**Comment by vaibhavsingh97** [comment]
Closing as it's fixed in #40
