### ISSUE TITLE
Use django-crispy-forms

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#141]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [X] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in our slack channel at https://opensourcehelp.slack.com/. Request invite [here](https://opensourcehelp.herokuapp.com)

**Description**:

Replace normal form tag with django-crispy-forms. Mainly /contests/.

**Comment by kurianbenoy** [comment]
Has this issue been closed ?

**Comment by anubhakushwaha** [comment]
Closing, as it has been merged with commit [7aa856a](https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/commit/7aa856a4255fceeb26a69c9c6b0c685848105cc6)
