### ISSUE TITLE
ValueError at /add_contest/

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#148]
**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in our slack channel at https://opensourcehelp.slack.com/. Request invite [here](https://opensourcehelp.herokuapp.com)

Submit any set of character but a valid date in dates in /contests/, [error](https://i.gyazo.com/9e010db33c4009dc8be0ee46e507bbec.png).

Show error *Enter a valid date* on the field.

**Comment by sparkle-sparkle** [comment]
Hi, I would like to do this for you :-)

**Comment by anubhakushwaha** [comment]
@sparkle-sparkle Working on this?

**Comment by sparkle-sparkle** [comment]
I've pushed on 18 October and haven't done anything after that on this issue.

**Comment by anubhakushwaha** [comment]
@tapasweni-pathak Does this issue has more requirements then sent by @sparkle-sparkle in #157  as I think it can be closed .

**Comment by tapaswenipathak** [comment]
@anubhakushwaha Looks like not, please retest if it is not reproducible please go ahead and close this. 🎉

**Comment by anubhakushwaha** [comment]
Closing, as now we are using a date picker which cannot lead to this error.
