### ISSUE TITLE
Bring thank you text in the center

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#150]
On /submit_contest/ page, bring the text in the center of the page i.e., both horizontally and vertically in the center of the page.
![thank you page](https://user-images.githubusercontent.com/4143778/31722152-07255f34-b439-11e7-89af-733e7bad29c3.PNG)

Also replace *Y* with *y*.

**Comment by GeekBoxIT** [comment]
I'll take this one!

**Comment by Glassig** [comment]
Is this fixed (ie should it be closed) or does it need a fix?

**Comment by mathagician** [comment]
This issue is not yet fixed, so I am taking it.

**Comment by kurianbenoy** [comment]
Can I still work on it?
