### ISSUE TITLE
Enable approve of contest from admin dashboard initial page [list of contests]

### ISSUE THREAD

**Issue by vaibhavsingh97** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#159]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in our slack channel at https://opensourcehelp.slack.com/. Request invite [here](https://opensourcehelp.herokuapp.com)

**Expected Behavior**:
Admin Dashoard show all details of contests like Name of contest, link of contests, etc

**Actual Behavior**:
Admin Dashoard does not show any details. Only contest name is shown

**Screenshots (if any)**:
![image](https://user-images.githubusercontent.com/8705386/31748944-53352396-b466-11e7-8ea5-eaaddcc778ad.png)

**Would you like to work on this issue?**
- [x] Yes
- [ ] No

**Comment by tapaswenipathak** [comment]
Can you please click on the contest name, it should show you all the fields then. Is this in your local deployment?

**Comment by vaibhavsingh97** [comment]
@tapasweni-pathak why extra click to get all the details?

**Comment by tapaswenipathak** [comment]
The directory structure works like

List of tables -(click on one)-> field return from object's unicode function ([in our case, contest name](https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/blob/predev/oshc/main/models.py#L29)) -(click on it)-> and you get all the details.

This looks good to me for this table.

**Comment by vaibhavsingh97** [comment]
@tapasweni-pathak  if user has submitted too many competition than it's not ideal that admin click on each competition to approve...he can see form main dashboard and approve the same :sweat_smile:
Please visit #160 to see the screenshot to get more insight

**Comment by tapaswenipathak** [comment]
Great! Why did you do it in parts? Also I changed the title of this issue a bit. Closed with 575c764765de1f4f5c7de863120dd9c222584415.

**Comment by vaibhavsingh97** [comment]
@tapasweni-pathak there was a reason I did in parts....please look at my comment in the PR

**Comment by tapaswenipathak** [comment]
#162 has changes required to show all the fields on the initial page and also approve from there. :)
