### ISSUE TITLE
Intergrate flake8 with Travis

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#163]
- [x] Add flake8 installation instruction in requiements.txt
- [x] Add the run command in .travis.yml
- [x] Test after enabling Travis for your fork
- [x] Submit a PR.

**Comment by mathagician** [comment]
@tapasweni-pathak I would like to work on this issue.

**Comment by vaibhavsingh97** [comment]
@mathagician Sure!! Just send PR fixing the same 😁

**Comment by mathagician** [comment]
@vaibhavsingh97 and @tapasweni-pathak have sent a PR for the same. Please review it.

**Comment by mathagician** [comment]
a new PR is https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/pull/178

Please see it

**Comment by tapaswenipathak** [comment]
Closed with #191.
