### ISSUE TITLE
Disallow the user to submit a contest name with all special characters

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#166]
I am able to submit a contest name having only special characters. A regex having a check that name should have either small characters or capital characters other than numbers or special characters should do.

**Comment by ghost** [comment]
I will give it a try :)

**Comment by vaibhavsingh97** [comment]
@wallid Sure!! I believe you can do it 😎. Send a PR fixing the issue

**Comment by ghost** [comment]
Could you familiarize me with the process of doing a fix.
My thoughts ....
1. Clone the repo 2. run 3. fix the bug 4. then create a pull request.

**Comment by vaibhavsingh97** [comment]
Yeah!! You already know the process 🎉 
Let me know if you want any further help to fix this issue

**Comment by ghost** [comment]
I'm getting an error after i run it in the browser. 500 internal server error in the centre container. I was unsure of how to setup the environment variable for DEBUG on windows 10
* all good run the migrations.

**Comment by ghost** [comment]
@vaibhavsingh97  I added regular expression, created my own branch then merged it to the predev. Tried pushing the predev but there was an authentication error.

**Comment by tapaswenipathak** [comment]
>I'm getting an error after i run it in the browser. 500 internal server error in the centre container. I was unsure of how to setup the environment variable for DEBUG on windows 10

> * all good run the migrations.

>@vaibhavsingh97 I added regular expression, created my own branch then merged it to the predev. Tried pushing the predev but there was an authentication error.

You figured out complete workflow. **woot!**
This last step only we can do, that's why you are getting authentication error. :)

**Comment by tapaswenipathak** [comment]
Only allowed characters for now, upper case, lower case, space and/or hyphen. Closed with ae7d124a700d571a2ab26372b605fefe469cc662.
