### ISSUE TITLE
New label needed

### ISSUE THREAD

**Issue by vaibhavsingh97** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#183]
Following labels are needed: 
- Work in Progress/ WIP : To tag PR which are not yet ready but work in progress

**Comment by nikhita** [comment]
@vaibhavsingh97 why not use the `status: In Development`?

**Comment by nikhita** [comment]
If it feels better, we can make `status: In Development` as `status: WIP` or something like that.

**Comment by tapaswenipathak** [comment]
Generic way which is followed is to have a [WIP] in your pull request, also I would not encourage too many [WIP] pull request, as it kind a blocks the issue. But if you have too many changes then WIP is super cool way to share that it is ongoing. Do you still need a separate label for this @vaibhavsingh97?

cc @nikhita.

**Comment by nikhita** [comment]
> Generic way which is followed is to have a [WIP] in your pull request

Agreed, this is a common way.

>  Do you still need a separate label for this @vaibhavsingh97?

If you still need one though, let me know though! :slightly_smiling_face:

**Comment by vaibhavsingh97** [comment]
@nikhita We can close this as traditional method looks good to me 👍
