### ISSUE TITLE
Update Travis and Coveralls badge link to predev branch

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#185]
Check the [markdown for README.md](https://raw.githubusercontent.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/predev/README.md). Both Travis badge and Coveralls badge points to develop branch. Change it to predev branch, like

- [ ] Travis  badge should point to: https://travis-ci.org/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io.svg?branch=predev
- [ ] Coveralls badge should point to: https://coveralls.io/repos/github/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/badge.svg?branch=predev

**Comment by chinmaykunkikar** [comment]
I'm on it. I've contributed many times but this is my first hacktoberfest contribution. So do I become a "first-timer-only"?
