### ISSUE TITLE
To make mailing list for http://opensourcehelpcommunity-predev.herokuapp.com/contests/

### ISSUE THREAD

**Issue by Logan1x** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#190]
**I'm submitting a ...**  (check one with "x")
- [x] feature request
**Description**:
[This](http://opensourcehelpcommunity-predev.herokuapp.com/contests/) idea is very good but we should add mailing list so that anyone who's subscribed gets notify when we add new contest. What do you guys think?

**Would you like to work on this issue?**
- [x] No

**Comment by tapaswenipathak** [comment]
:wave: Slack is one way to stay updated. In future user would sign in and send a mail for a reminder for the content.
