### ISSUE TITLE
Integrate all social channels 

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#2]
* Find a proper place for this on the UI.

**Comment by manishpatel005** [comment]
Hi Tapasweni. I am made changes to index.html to include the social channels. Please tell me how to push it.

**Comment by tapaswenipathak** [comment]
@manishpatel005 You need to fork the repository, push the changes to your fork and then create a pull request on this repository. 

[These](https://help.github.com/articles/creating-a-pull-request-from-a-fork/) [two](https://help.github.com/articles/creating-a-pull-request/) guides will help.

**Comment by melrick8196** [comment]
Is this about integrating just the social buttons or something else?

**Comment by tapaswenipathak** [comment]
@melrick8196 Yes, you got it correct. The way you feel it would look good with the current design of the website. I really like font awesome icons. But if you have something better in your mind, feel free to submit a pull request with the changes.

**Comment by anubhakushwaha** [comment]
Closing.Fixed via #16
