### ISSUE TITLE
New Design for Website

### ISSUE THREAD

**Issue by vaibhavsingh97** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#21]
![image](https://cloud.githubusercontent.com/assets/8705386/26758587/36641370-4900-11e7-9c58-b58c2661da8d.png)

**Comment by vaibhavsingh97** [comment]
![image](https://cloud.githubusercontent.com/assets/8705386/26758763/ce2240ce-4905-11e7-88fc-093dc90dbd8c.png)

**Comment by vaibhavsingh97** [comment]
![image](https://cloud.githubusercontent.com/assets/8705386/26758874/ccc64eba-4909-11e7-86cb-bdd0092bdb04.png)

**Comment by tapaswenipathak** [comment]
@vaibhavsingh97 Thanks! 

But I will prefer our current design, less colors, simple. Plus we do not need this much of space for information on the website, very few things on the front page of the website. I have collected few designs from web for sessions page and other feature of the website, I will be putting this in the task list in some time. Feel free to pick it up and create. You can always discuss your ideas more on #oshc-dev Slack channel or create an issue here.

**Comment by vaibhavsingh97** [comment]
@tapasweni-pathak These designs are simple and built on one color scheme (Color picked from the logo). This UI looks interactive but the old designs are not. But if you want we will work on features of the website rather than look and feel.

**Comment by tapaswenipathak** [comment]
@vaibhavsingh97 I agree. But we really do not need this much of space for the front page(s) and wait for a while, it will look interactive too. Thanks again! :) :sparkles: 

Feel free to raise issues for the things you don't like, it will help a lot! 

One more thing, do you have some time to chat, I would love to discuss what we are planning further and how you can lead a few things for us?

**Comment by vaibhavsingh97** [comment]
@tapasweni-pathak Sure! i pinged you on slack

**Comment by vaibhavsingh97** [comment]
Fixed #33
