### ISSUE TITLE
Remove open in new tab for links

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#210]
Remove `target=_blank` [from](https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/blob/predev/oshc/main/templates/base.html#L37), for
- [ ] Request a session
- [ ] Contests
- [ ] Journey

**Comment by Nickatak** [comment]
Hello! I saw that the above two PR's were closed due to non-first-timers (still, it was awesome seeing an example of a solid PR).  Do you mind if I work on this? :D

**Comment by anubhakushwaha** [comment]
@Nickatak Yes go ahead.

**Comment by nirmaldalmia** [comment]
I would like to work on this issue. I am new to open source but I've been working on websites for quite some time now. Let me know if the issue is still open.
Do I have to delete all the target="_blank" tags from the page or only 3 mentioned above?

**Comment by tapaswenipathak** [comment]
👋 @nirmaldalmia from `Request a session`, `Contests` and `Journey`.

**Comment by nirmaldalmia** [comment]
@tapasweni-pathak Is the issue already solved? Because I don't see any target="_blank" in the above mentioned tags. 
Also went through the PR submitted before my comment which says the issue is resolved.
Let me know if there is still anything I can do.
