### ISSUE TITLE
Change view session link

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#213]
From https://www.youtube.com/channel/UC1_IAby-9me3iICtxuiDL5Q to https://www.youtube.com/channel/UC1_IAby-9me3iICtxuiDL5Q/videos.

<img width="821" alt="screen shot 2017-12-24 at 1 01 56 pm" src="https://user-images.githubusercontent.com/4143778/34324990-ad12349e-e8aa-11e7-803a-d063a35ea8e9.png">

**Comment by Justme764** [comment]
Hello @tapasweni-pathak   20+ years in IT (hardware side) so this side is all new to me. I have taken the classes and now want to see if I can contribute.  I see you have a good first timer.  Can you help me get started?  Thanks

**Comment by Logan1x** [comment]
@Justme764 what help you needed?

**Comment by tapaswenipathak** [comment]
> Hello @tapasweni-pathak 20+ years in IT (hardware side) so this side is all new to me. I have taken the classes and now want to see if I can contribute. I see you have a good first timer. Can you help me get started? Thanks

:wave: @Justme764, sure, please go ahead and pick any [first-timers-only](https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/labels/first-timers-only) issue. You can join the [Slack channel](https://opensourcehelp.herokuapp.com/) if you have any further questions. Feel free to tag me on Slack or on GitHub for your questions.
