### ISSUE TITLE
User should be able to register

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#25]
Needed for #24.

**Comment by vaibhavsingh97** [comment]
@tapasweni-pathak I am interested in working on this issue. Will send PR in a day or two

**Comment by vaibhavsingh97** [comment]
@tapasweni-pathak @amarlearning @nikhita Where should the register/login button should be placed?
I was thinking to check the user state and if the user hasn't logged in till now than there should be a popup to register/login and if the user has closed the popup than he/she can register by clicking join now which would be present below the header text. For reference image is shown below.
![screenshot from 2017-06-22 10-35-17](https://user-images.githubusercontent.com/8705386/27418097-953dfb42-5736-11e7-908a-39a67643ddec.png)
Please share your thoughts on this

**Comment by tapaswenipathak** [comment]
We will start with something very simple like having a simple form through which user can register and login and see something only for them. We will have it on the top bar itself on the right. Something [like](http://mycodeschool.com/work-outs)? Please go ahead if you feel something can be better than this.
