### ISSUE TITLE
Allow the user to request a session

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#26]
Can use a typeform or something similar first, next have it in our database.

**Comment by amarlearning** [comment]
@tapasweni-pathak since we don't have any user registration as of now. So going with Typeform or Google forms. I can think of these form fields as of now _Name_, _Email_, _Session Subject_, _Session Details_, _Request From_, _Additional Comments_.

Taking this one. Need your inputs on this.

**Comment by tapaswenipathak** [comment]
Sure! go ahead with Typeform, try to keep the theme, colors in sync with the current state of website. Have a look at [this](http://www.mycodeschool.com/videos), on the front page right now you need to link request a session button to this form but later we will link to sign in/sign up.


Also having a field for web presence for both the requester and the person whose session is requested will help.

I can think of following fields:

1. Your name
2. Your email id 
3. Your website (or any link for web presence which can verify this person exist)
4. Name of person you would like us to invite in a session (need to think of a small title for this.)
5. Email id of 4 (a better title for this too)
6. Website of 4 (same)
7. What questions you have for them?
8. Would you want them to answer anything specific? 

@amarlearning @nikhita Do you think we can have something more?

For this you would need credentials I guess, let me know I will ping you on Slack.

**Comment by vaibhavsingh97** [comment]
@amarlearning What are you up to? Please tell me your progress or else I can create form in Django and integrate to the website

**Comment by amarlearning** [comment]
@vaibhavsingh97 if space is not a problem, you can create a form for that.

**Comment by vaibhavsingh97** [comment]
@tapasweni-pathak @amarlearning I am working on this issue! Will add PR soon :)

**Comment by nikhita** [comment]
Moving some of the brain-storming part to slack. https://opensourcehelp.slack.com/archives/C53RVADHC/p1499109900041539
