### ISSUE TITLE
Adding template for footer

### ISSUE THREAD

**Issue by vaibhavsingh97** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#34]
According to DRY Principle, The aim should be reducing the repetition of information.
The footer is present in the index.html file and in future we will have more pages, so to avoid repetition we will add this in the template.

Existing behavior: Footer code snippet is present in the index.html
Actual Behaviour: Footer should be present as a template so that we can just use the code-block

**I am interested in working on this issue**

**Comment by tapaswenipathak** [comment]
@vaibhavsingh97 Sure, please go ahead.

Please base your code changes on https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/pull/33. Most probably we will be merging this with few changes, to avoid any extra effort from your end.

**Comment by vaibhavsingh97** [comment]
@tapasweni-pathak Sure!
