### ISSUE TITLE
Different screen compatibility

### ISSUE THREAD

**Issue by vaibhavsingh97** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#39]
Actual Behavior:
![image](https://user-images.githubusercontent.com/8705386/27342161-eecb1fa4-55fc-11e7-8bda-386ba11cef46.png)
![image](https://user-images.githubusercontent.com/8705386/27342182-fe356562-55fc-11e7-8428-c2345d567f87.png)
![image](https://user-images.githubusercontent.com/8705386/27342195-0aed74de-55fd-11e7-8020-4a6d1046f478.png)
Expected Behaviour: Website sholud adapt different screens
**Yes! I am interested in working on this issue**

**Comment by tapaswenipathak** [comment]
Sure, please go ahead.
