### ISSUE TITLE
Avoid Redirection

### ISSUE THREAD

**Issue by vaibhavsingh97** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#42]
We should make a  script which will fetch all the video from the channel and display on a page.
**Actual Behaviour**:  opening `session` tab redirects to youtube page  
**Expected Behaviour**: opening `session` page should display videos on the page itself.  

**I am interested in working on this issue**

**Comment by vaibhavsingh97** [comment]
@nikhita  @jarifibrahim @tapasweni-pathak Need your views. Should I start working on this issue?

**Comment by tapaswenipathak** [comment]
@vaibhavsingh97 We have an [issue for this](https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/issues/1). See the link I added in that issue, does that help you to think for a better design?

Closing this one as we can discuss on #1.
