### ISSUE TITLE
Add Admins to settings.py

### ISSUE THREAD

**Issue by jarifibrahim** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#49]

**Comment by Utsal20** [comment]
Hi, can I try this? Would appreciate a bit more guidance. Thanks!

**Comment by nikhita** [comment]
@Utsal20 Yes, you can work on this! :tada: 

For any queries/guidance, you can either ask here in this issue or reach out to me (@nikhita) or @jarifibrahim on slack. For joining the slack, you can get an invite here: https://opensourcehelp.herokuapp.com/. :)

**Comment by jarifibrahim** [comment]
@Utsal20 See this - https://docs.djangoproject.com/en/1.11/ref/settings/#admins
You need to add the `ADMINS` setting to the `settings.py` file.
Add the following admins.
**Tapasweni Pathak** - **tapaswenipathak@gmail.com**
**Nikhita Raghunath** - **nikitaraghunath@gmail.com**
**Ibrahim Jarif** - **jarifibrahim@gmail.com**

**Comment by Utsal20** [comment]
Got it, thank you!

**Comment by vaibhavsingh97** [comment]
@jarifibrahim @nikhita @tapasweni-pathak please close this issue  as issue resolved in #64
