### ISSUE TITLE
Disallow re registration from same email id

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#52]
I am able to re register with the same email id.

**Comment by mish24** [comment]
@tapasweni-pathak I can fix this too if it's free

**Comment by vaibhavsingh97** [comment]
@mish24 Are you working on this issue?

**Comment by sarthakkapoor21** [comment]
is this issue still open? @tapasweni-pathak @vaibhavsingh97

**Comment by vaibhavsingh97** [comment]
@sarthakkapoor21 Yes! you can work on this issue as there is no response from @mish24

**Comment by anubhakushwaha** [comment]
@sarthakkapoor21 Working on this?

**Comment by vaibhavsingh97** [comment]
@anubhakushwaha As we are now having custom-registration-model so we will take there of this there. But if @sarthakkapoor21 want to contribute than he can contribute there

**Comment by anubhakushwaha** [comment]
Closing this for now, as we are switching to custom-registration model

**Comment by tapaswenipathak** [comment]
@anubhakushwaha should we keep this and #108 open as they are issues, if custom-registration model fixes these two we will close this, otherwise not?

**Comment by anubhakushwaha** [comment]
@tapasweni-pathak +1

**Comment by vaibhavsingh97** [comment]
@tapasweni-pathak @anubhakushwaha Before sending PR I would create the issue with the designs and use cases for custom registration model. So we can close this after the custom-registartion-model 😄

**Comment by tapaswenipathak** [comment]
Closing this, retesting and would create new if I am able to sign in.

**Comment by vaibhavsingh97** [comment]
@tapasweni-pathak Allauth takes care of this so no worry 😅.

**Comment by tapaswenipathak** [comment]
I know allauth should handle this, would retest and create new if I am able to sign in.
