### ISSUE TITLE
Show password strength indicator

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#53]

**Comment by bikrambhattacharya** [comment]
@tapasweni-pathak  how to find the file related to the issue? I can't find help needed.

**Comment by jarifibrahim** [comment]
@bikrambhattacharya [This](http://opensourcehelpcommunity-dev.herokuapp.com/accounts/register/) is the user registration form. You'll have to add password strength indicator to this form. The HTML code of the registration form is in `oshc/main/templates/registration/registration_form.html` file.

**Comment by bikrambhattacharya** [comment]
@jarifibrahim Okay I will try to add one.

**Comment by tapaswenipathak** [comment]
@bikrambhattacharya Were you able to progress a bit? Let us know if you need some more help on #oshc-dev channel on Slack.

**Comment by vaibhavsingh97** [comment]
@bikrambhattacharya Are you still working on this issue?

**Comment by bikrambhattacharya** [comment]
@vaibhavsingh97   I couldn't figure out how to add strength indicator.

**Comment by vaibhavsingh97** [comment]
@bikrambhattacharya You can take help from this blog http://blog.birdhouse.org/2015/06/16/sane-password-strength-validation-for-django-with-zxcvbn/comment-page-1/

**Comment by bikrambhattacharya** [comment]
@vaibhavsingh97  Thank you

**Comment by vaibhavsingh97** [comment]
@bikrambhattacharya Any progress?

**Comment by sarthakkapoor21** [comment]
Is this issue still open? @vaibhavsingh97 @tapasweni-pathak

**Comment by vaibhavsingh97** [comment]
@sarthakkapoor21 @bikrambhattacharya is working on this issue. You can work on other [issues](https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/issues)

**Comment by bikrambhattacharya** [comment]
@vaibhavsingh97  I hope i will be able to make a pull request within next two days, thank you

**Comment by jarifibrahim** [comment]
@bikrambhattacharya The link posted by @vaibhavsingh97 refers to password strength checking at the server side. We could compute the strength at the server, but it would be difficult.

A much simpler approach is to use client side password strength checking. The following pages show how to implement client side password strength calculation. 

https://www.aspsnippets.com/Articles/Password-Strength-validation-example-using-JavaScript-and-jQuery.aspx

http://jsfiddle.net/HFMvX/

**Comment by bikrambhattacharya** [comment]
@jarifibrahim  Thank you, I am also using RegExp for checking, my code will be similar to this.

**Comment by bikrambhattacharya** [comment]
@jarifibrahim @vaibhavsingh97  what if the user use a password like name@1234? should I include an another condition if the password contains user's name?

**Comment by jarifibrahim** [comment]
@bikrambhattacharya If you could add it, it would be great. :)

**Comment by bikrambhattacharya** [comment]
@jarifibrahim @vaibhavsingh97  I have added a strength meter. where should I place it? below the password field?

**Comment by vaibhavsingh97** [comment]
@bikrambhattacharya Yes, It should appear when user type password

**Comment by bikrambhattacharya** [comment]
@vaibhavsingh97  okay
