### ISSUE TITLE
Change navbar and footer color back to #eeeeee

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#56]
With new design push this was also changed, black looks too strong to eyes. Going with the original theme, blue, white and grey and light shades of these should do for all elements on the website.

**Comment by mish24** [comment]
@tapasweni-pathak I would like to work on this :)

**Comment by amarlearning** [comment]
@tapasweni-pathak you really want to change the color to `#EEEEEE` :stuck_out_tongue:  I think the current theme color looks good :sweat_smile:

**Comment by mish24** [comment]
@amarlearning No? :D

**Comment by amarlearning** [comment]
@mish24 I like the current color combination. but since it's an issue :+1:

**Comment by vaibhavsingh97** [comment]
@mish24 @amarlearning Me too like the current theme :)

**Comment by tapaswenipathak** [comment]
@amarlearning @vaibhavsingh97 Sorry I opened this issue without discussion but I really want the website to be on the light color side, that's what I have seen on most websites. I know even I like Black but still for visitors of the website I would prefer whitish theme with light colors, they look better to eyes. If you both not at all like #eeeeee we can have a vote, I'll vote for #eeeeee. :) 

May be we can consult someone who knows this better, I think @sandarumk knows someone?

Edit:

Taking it over to Slack in the dev channel. :)

**Comment by tapaswenipathak** [comment]
Everyone likes the current theme, I don't know why I still have a feel for #eeeeee, closing this issue anyway. 😅
