### ISSUE TITLE
Upcoming Sessions Shows the sessions which are already over

### ISSUE THREAD

**Issue by sandarumk** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#65]
In the upcoming session section in the website, the current session which shows at the top is a one which is already finished.

**Comment by Logan1x** [comment]
Is it done @tapasweni-pathak ?

**Comment by vaibhavsingh97** [comment]
@Logan1x yeah! Refer to #66

**Comment by Logan1x** [comment]
@vaibhavsingh97 @tapasweni-pathak  we should put it but not as session reminder but as lists that having session which are already done. what do you guys think?
