### ISSUE TITLE
Need instructions for installing Django

### ISSUE THREAD

**Issue by s24569** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#7]
I need help with installing Django. I already succeeded in installing python and pip but for whatever reason I run into trouble when it comes time to put Django onto my computer.
![screen shot 2017-05-02 at 9 44 30 am](https://cloud.githubusercontent.com/assets/11892387/25620394/40b1458a-2f1c-11e7-9211-aafcd56482b1.png)

**Comment by tapaswenipathak** [comment]
@s24569 Try adding **sudo** before the command.

**Comment by s24569** [comment]
It worked and it says that Django has been installed. The list of instructions on the README say to go inside the main Django app but I don't see an icon for it or anything. How do I go about getting into the Django app itself?

**Comment by tapaswenipathak** [comment]
@s24569 You need to clone the repository. [This](https://help.github.com/articles/cloning-a-repository/) will help. After you are done feel free to submit a pull request with the steps which are missing in the readme.
