### ISSUE TITLE
Store sessions in database

### ISSUE THREAD

**Issue by jarifibrahim** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#73]
Save information about the upcoming sessions and render those on the home page.
Information about sessions can be added/updated using the `Admin` interface.

**Comment by jarifibrahim** [comment]
@amarlearning @tapasweni-pathak @vaibhavsingh97 What do you think?

**Comment by vaibhavsingh97** [comment]
Sounds good to me :+1: :smiley:

**Comment by amarlearning** [comment]
@jarifibrahim How much free space do we get on free Heroku container?

**Comment by jarifibrahim** [comment]
@amarlearning 10,000 rows

**Comment by vaibhavsingh97** [comment]
@jarifibrahim @amarlearning I am interested in solving this issue

**Comment by tapaswenipathak** [comment]
This is ✨.
