### ISSUE TITLE
Why OSHC?

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#76]
Need suggestions on how should we link this to the main website. Not everything can go in "our mission" on the main website. I am not able to figure out what could be the best way for a detailed writeup on "about us" or "about oshc".

Few options are

- [ ] A blog in form of markdown file in this repository, linked with element on footer of the website
- [ ] Page on the website itself attached with a link on the footer
- [ ] Adding it on wiki in this repository [visibility issues]

Please suggest if more options are there to have this.

**Comment by vaibhavsingh97** [comment]
I will go with second option 
"Page on the website itself attached with a link on the footer"

**Comment by Logan1x** [comment]
Second One also looks fine to me.

**Comment by tapaswenipathak** [comment]
@sandarumk As discussed you will be pushing this fix. I have assigned this to you. Also it would be good to have @nikhita for this. :)

**Comment by sandarumk** [comment]
I agree with the others with the second option. I will have the write up ready at the end of this week and then work on the improvements with @nikhita .

**Comment by nikhita** [comment]
@sandarumk Awesome, please ping me on Slack whenever you are done with the post and we can collaborate on this. :)

**Comment by sandarumk** [comment]
I just started writing this. Apologies for being very late. @nikhita @tapasweni-pathak I have a question though. Should it be written on my perspective or open source communities perspective. What I meant was I can write some thing like the below two options. 

- I saw the problem of lack of knowledge and started the community
- The community is started to rectify the issue of lacking the knowledge

Personally, I would like the second approach as it sounds more professional. But it seems that first one has a personal touch in it. Which would you prefer?

**Comment by nikhita** [comment]
> Apologies for being very late

Totally ok! :)

> Which would you prefer?

I'd say write it from your perspective but replace all the "I" and "me" parts with "we" and "us". That way we can have professionalism with a personal touch. :)

**Comment by tapaswenipathak** [comment]
> Apologies for being very late
>> Totally ok! :)

💯 

When it comes to writing a why OSHC on the website itself, I prefer speaking from Organization perspective. I would avoid any personal touch, concentrate more on the mission and vision of the org. I go with second.
