### ISSUE TITLE
Add Travis CI Badge to README.md

### ISSUE THREAD

**Issue by jarifibrahim** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#80]
Add Travis CI badge to Readme.md. The badge can be found on [this](https://travis-ci.org/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/) page.

**Comment by Logan1x** [comment]
@jarifibrahim i would like to work on this.

**Comment by Logan1x** [comment]
@jarifibrahim done #81
