### ISSUE TITLE
Add coveralls.io badge to README.md

### ISSUE THREAD

**Issue by jarifibrahim** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#83]
Add coveralls.io badge to README.md file which can be found on https://coveralls.io/github/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io

**Comment by sarthakkapoor21** [comment]
@jarifibrahim could you help me get started on this?

**Comment by jarifibrahim** [comment]
@sarthakkapoor21 You need to add the `badge` (fancy name for an image) for the coveralls.io build.

1. Go to [this](https://coveralls.io/github/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io) page.
2. There is a `badge` section on the right-hand side. Click on the `embed` button in the badge section.
3. Copy everything in the `markdown` section.
3. Paste the content you just copied in the `README.md` file (in the top section, below the name of the project).

**Comment by coding-sunshine** [comment]
Added PR

**Comment by nikhita** [comment]
I just noticed that @sarthakkapoor21 had mentioned about working on this issue before.

@coding-sunshine It is great that you submitted a PR (very much appreciated!). However, if someone is already working on a PR, it is better to usually ask if they are still working on it before sending a PR. Helps in avoiding duplicated efforts. :smile: 

@sarthakkapoor21 Feel free to work on any of the other issues!

**Comment by nikhita** [comment]
Fixed in #88.
