### ISSUE TITLE
Integrate Hound CI

### ISSUE THREAD

**Issue by vaibhavsingh97** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#87]
**Description**:

[Hound CI](https://houndci.com/) is a hosted service that comments on the style violations of the pull requests. This helps to review and maintain a clean codebase.

**Would you like to work on this issue?**
- [x] Yes
- [ ] No

**Comment by vaibhavsingh97** [comment]
@tapasweni-pathak @nikhita @jarifibrahim your views on this issue. If you agree to accept please grant Hound CI access

**Comment by nikhita** [comment]
LGTM! :+1: I'll still let @tapasweni-pathak and @jarifibrahim confirm once though. :)

**Comment by jarifibrahim** [comment]
@vaibhavsingh97 I've enabled Hound CI. I'll send a PR to test it.

**Comment by jarifibrahim** [comment]
@vaibhavsingh97 I created a PR https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/pull/90 but Hound CI was not triggered. I think we'll have to add the `.hound.yml` config file.

**Comment by vaibhavsingh97** [comment]
@jarifibrahim Yes we need .hound.yml to trigger Houng CI
See this
![image](https://user-images.githubusercontent.com/8705386/28566959-6d4cd946-714e-11e7-9e8b-72be7ae38cf3.png)

**Comment by vaibhavsingh97** [comment]
@jarifibrahim Should i send Hound CI PR?

**Comment by jarifibrahim** [comment]
@vaibhavsingh97 Yes. I'll close https://github.com/OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io/pull/90.
