### ISSUE TITLE
Migration form django-registration-redux to django-all-auth

### ISSUE THREAD

**Issue by vaibhavsingh97** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#95]
**Description**:
Benefits of using our own custom registration model
- Customizable
- Easy to maintain
- Easy bug fix as we have written the code :wink: 

**Would you like to work on this issue?**
- [x] Yes
- [ ] No

**Comment by vaibhavsingh97** [comment]
cc: @nikhita @tapasweni-pathak @amarlearning @anubhakushwaha @jarifibrahim

**Comment by tapaswenipathak** [comment]
@vaibhavsingh97 @jarifibrahim  Is this done?

**Comment by vaibhavsingh97** [comment]
@tapasweni-pathak I am working on this, I will try to update as soon as  possible 😄
