### ISSUE TITLE
Ideas on making the website user-specific

### ISSUE THREAD

**Issue by anubhakushwaha** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#96]
**FEATURE REQUEST**

**Description**:

We are planning to make the website more user-interactive and ideas will be appreciated 

- Show all the sessions on the website itself so that the user can bookmark those sessions for future.

- Functionality to view previous requests for sessions

- Add a "My Journey" section, where the developers can add their experience with open source 

- We can also plan on adding labels on issues with points(coins) on issues which could give the developers their own dashboard of how many points won,etc.

These are just some ideas, whether implementable or not at this point, we would really appreciate involvement of as many minds as possible to bring out something productive, feel free to comment with your suggestions regarding the existing features or any new idea that you can think of.

**Comment by anubhakushwaha** [comment]
@tapasweni-pathak  @sandarumk  @vaibhavsingh97  @amarlearning  @jarifibrahim  @nikhita  Please have a look and let's try to get the most out of it :)

**Comment by vaibhavsingh97** [comment]
1. We can have badges like rookie, Editor, Contributor, Popular, etc based on the contribution in our website. 
2. We can have `xP` in the profile so we can have top 10 contributors based on the `xP`
#### How we calculate xP
- We will take help of Github and fetch organizations/ forked repositories. Based on the issues/commit/ PR merged//PR created we will gave points. This will be refreshed via analyze button (allowed to refresh per 24 hours).
3. Level of experience can be added based on the xp
For example:

| Level | Experience |
|-------|------------|
| 0      | 0            |
| 1      | 200        |
| 2      | 400        |
| 3      | 800        |

**Comment by anubhakushwaha** [comment]
@vaibhavsingh97  How do you propose analysis based on contributions outside of our projects? Let me know your thoughts, what I was thinking was to label the open issues with "points" and certain points on opening a new issue and sending a PR, but it would be then confined to projects just limited to OSHC, @nikhita  @vaibhavsingh97  any thoughts on this?

**Comment by vaibhavsingh97** [comment]
@anubhakushwaha we will ask user to link with Github and fetch all the information of user including his PR, issues, etc. We will then use the data for further calculation.

**Comment by anubhakushwaha** [comment]
@vaibhavsingh97 Yeah that's exactly we need to figure out right? How will the scoring happen? On one hand someone can solve many minor issues as compared to someone with just one major issue in any project, how will the weighting happen without manual intervention? I hope I was clear, let me know if you have any ideas?

**Comment by vaibhavsingh97** [comment]
@anubhakushwaha Here comes the machine learning/AI  + NLP which evaluate that the person has solved the major issues or minor issues and grade the points to the person. Right now, we can track only when we collaborate with other organizations and we can then 
>  label the open issues with "points" and certain points on opening a new issue and sending a PR  

This way we can track but limited to certain projects :disappointed:

**Comment by tapaswenipathak** [comment]
@anubhakushwaha All suggestions are 🌟 and implementable. Can you please open a separate issue for all of them. Discussing on issue level is easier and then we can also assign or pick issues.

**Comment by anubhakushwaha** [comment]
Closing since it has been handled separately in #115, #126 and #112 .
