### ISSUE TITLE
Ideas on making the website more helpful 

### ISSUE THREAD

**Issue by anubhakushwaha** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#97]
**FEATURE REQUEST**

**Description**:

We are planning to make the website more useful for everyone, ideas are highly appreciated. Few of them are:

- To show all the requests from people so that others can view them and upvote them, this way we could process the requests in a particular order as per the demand

- We can also have a section for "star contributor" of the month which would encourage new developers to come forward and contribute to open-source

These are just some ideas, whether implementable or not at this point, we would really appreciate involvement of as many minds as possible to bring out something productive, feel free to comment with your suggestions regarding the existing features or any new idea that you can think of.

**Comment by anubhakushwaha** [comment]
@tapasweni-pathak @sandarumk @vaibhavsingh97 @amarlearning @jarifibrahim @nikhita Please have a look and let's try to get the most out of it :)

**Comment by nikhita** [comment]
@anubhakushwaha What a wonderful idea!

> We can also have a section for "star contributor" of the month which would encourage new developers to come forward and contribute to open-source

Does this mean we'll have a "points" based system? If you contribute more, you get more points?

Fwiw, we have a gamification system like this in Kubernetes called "k8s Port" and it seems to have encouraged people to contribute more! I am not aware of the impact in exact terms but there seems to be a general positive consensus around it. :)

**Comment by nikhita** [comment]
@anubhakushwaha Sorry, the other issue #96 mentions about points. Spoke too soon. :)

**Comment by anubhakushwaha** [comment]
@nikhita  Haha no issues, ooh it's amazing that it showed a positive impact, we would not keep it to a high level, just another field which would contain the points earned

**Comment by vaibhavsingh97** [comment]
We can have **chat bot** which help newbies to get useful resource in order to get started with open source development. Also, if the chat bot not able to help the new developer than he can contact human anytime and choose anyone from the top 30 based on the experienced earned

**Comment by Logan1x** [comment]
@nikhita  @anubhakushwaha  were you talking about something like this?

![screenshot from 2017-09-15 13-23-01](https://user-images.githubusercontent.com/10944610/30472408-c0d6b896-99eb-11e7-8e86-8b536e17a083.png)
![screenshot from 2017-09-15 13-24-07](https://user-images.githubusercontent.com/10944610/30472409-c17fd5b6-99eb-11e7-9ab3-6165d0a2f8f5.png)

this feature is great!

[website link](https://coala.io/#/getinvolved)

**Comment by tapaswenipathak** [comment]
@vaibhavsingh97 I am all up for chatbot. A slack or/and one on the website. A basic one which answers questions like I know a, b, c, how should I get started with and with what? I would be happy to work with you on this. Can you create a separate issue for this?

@anubhakushwaha Rating contributors is 💯. Always had this in mind. But this needs a lot of discussion have created #112 to take the discussion forward.

**Comment by tapaswenipathak** [comment]
Created a separate issue, so closing this one. Also decisions about the session we keep to us.
